### ISSUE TITLE
Add additional client kwargs

### ISSUE THREAD

**Issue by philsupertramp** [philsupertramp/chain-smoker#26]
Would be cool to be able to add default values for parameters of `ApiClient` request methods.
The idea would be to write configuration, e.g.
```yaml
client:
  base_url: example.com
  kwargs:
    timeout: 15
    stream: false
```
Options documented in https://requests.readthedocs.io/en/latest/api/#requests.request

Then pass it into the method every time we execute a request

https://github.com/philsupertramp/chain-smoker/blob/80144db95887624f9828099a2812b213c013a4e1/src/chain_smoker/api_client.py#L30

by enhancing the passed `kwargs`
```python
**{**self.default_kwargs, **kwargs}
```
or
```python
final_kwargs = self.default_kwargs.copy()
final_kwargs.update(kwargs)
**final_kwargs
```
