### ISSUE TITLE
Add cookies

### ISSUE THREAD

**Issue by philsupertramp** [philsupertramp/chain-smoker#8]
We need support for

- [ ] payload cookies
- [ ] expected response cookies

Example:  
Supposedly endpoint `/step-6-of-10` requires two cookies, a `key` cookie and a `sessionId` cookie and responds with a `progress` cookie, then a test for this might look like this:

```yaml
example_test:
  endpoint: /step-6-of-10
  method: get
  payload_cookies:
    - domain: example.com
      max_age: 2022-02-02T10:00:00+01:00:00
      name: key
      value: value
    - domain: example.com
      max_age: 2022-02-02T10:00:00+01:05:00
      key: sessionId
      value: 420
  response_cookies:
    - domain: example.com
      max_age: Session
      name: progress
      value: 60
```
